//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_notaria
    {
        public int cod_notaria { get; set; }
        public string direccion { get; set; }
        public int telefono { get; set; }
        public Nullable<int> telefono_2 { get; set; }
        public Nullable<int> fax { get; set; }
        public string email_notaria { get; set; }
        public string email_meson { get; set; }
    }
}
