//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_notaria
    {
        public string cod_notaria { get; set; }
        public string direccion { get; set; }
        public int telefono { get; set; }
        public Nullable<int> telefono_2 { get; set; }
        public Nullable<int> fax { get; set; }
        public string email_notaria { get; set; }
        public string email_meson { get; set; }
    }
}
