//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_atencion_clientes
    {
        public int cod_medicion { get; set; }
        public System.DateTime fecha_medicion { get; set; }
        public System.DateTime tiempo_medido { get; set; }
    }
}
