//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_tramites_realizados
    {
        public int cod_medicion { get; set; }
        public int cant_tramites { get; set; }
        public System.DateTime fecha_inicio_medicion { get; set; }
        public System.DateTime fecha_term_medicion { get; set; }
    }
}
