//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_tramites_realizados
    {
        public int cod_medicion { get; set; }
        public int cant_tramites { get; set; }
        public System.DateTime fecha_inicio_medicion { get; set; }
        public System.DateTime fecha_term_medicion { get; set; }
    }
}
