//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int cod_reserva { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string motivo { get; set; }
        public string estado { get; set; }
        public string usuario_rut { get; set; }
        public int cod_tramite { get; set; }
    
        public virtual tipo_tramite tipo_tramite { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
