//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_tramite
    {
        public int cod_tramite { get; set; }
        public string nombre_tramite { get; set; }
        public string descripcion { get; set; }
        public string requisitos { get; set; }
        public int precio { get; set; }
        public string cod_template { get; set; }
    }
}
