//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string rut { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public int fono { get; set; }
        public string contraseña { get; set; }
        public string email { get; set; }
        public string cod_comuna { get; set; }
    }
}
