//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas_presencial
    {
        public int cod_venta { get; set; }
        public int amount { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string rut_persona { get; set; }
        public string estado { get; set; }
        public int doc_emitido_cod_documento { get; set; }
    
        public virtual doc_emitido doc_emitido { get; set; }
    }
}
