//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_de_Clases.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas_online
    {
        public string cod_venta { get; set; }
        public int amount { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string cod_documento { get; set; }
    
        public virtual doc_emitido doc_emitido { get; set; }
    }
}
